export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  PASSWORD_RESET_REQUEST: '/password-reset-request',
  PASSWORD_RESET: '/password-reset',
  DASHBOARD: '/',
  TASKS: '/tasks',
  TASK: (id: string) => `/tasks/${id}`,
  TASK_GRAPH: '/graph',
  USERS: '/users',
  DOCS: '/docs',
  DOCS_ABOUT: '/docs/about',
  DOCS_FAQ: '/docs/faq',
  DOCS_GUIDE: '/docs/guide',
} as const
